# Generated by Django 5.1.5 on 2025-01-28 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apoderado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("preferencia_notificacion", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("hora_entrada_regular", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nivel", models.CharField(max_length=50)),
                (
                    "establecimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="MainApp.establecimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_entrada", models.TimeField()),
                ("limite_atraso", models.TimeField()),
                ("dia_semana", models.CharField(max_length=20)),
                (
                    "establecimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_horario",
                        to="MainApp.establecimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "apoderado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="MainApp.apoderado",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="MainApp.curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atraso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_llegada", models.DateTimeField()),
                ("justificacion", models.TextField(blank=True, null=True)),
                ("justificado", models.BooleanField(default=False)),
                ("fecha", models.DateField()),
                (
                    "estudiante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atrasos",
                        to="MainApp.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HuellaDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_huella", models.BinaryField()),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huellas_digitales",
                        to="MainApp.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inasistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("justificacion", models.TextField(blank=True, null=True)),
                ("justificada", models.BooleanField(default=False)),
                ("tipo_inasistencia", models.CharField(max_length=50)),
                (
                    "estudiante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inasistencias",
                        to="MainApp.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro_id", models.IntegerField()),
                ("tipo_registro", models.CharField(max_length=50)),
                ("fecha_envio", models.DateTimeField()),
                ("estado", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
                (
                    "apoderado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="MainApp.apoderado",
                    ),
                ),
            ],
        ),
    ]
